guard and logging for error seen in prod
ministryofjustice/make-recall-decision-ui pull request #945
Opened 2023-10-23 16:42 UTC by robinandrewdevilliers

2023-10-23 17:02 UTC, DarrenW-HMPPS requested changes

2023-10-24 08:56 UTC, robinandrewdevilliers commented on server/controllers/recommendation/reviewPractitionersConcernsController.ts
> +        logger.warn(`Delius selected value not found amongst available options: ${s}`)
P11 - personal information?   what is being logged is whatever was previously selected, which is one of a enumerated set of values, so not free-form text entry.  Also  the log statement doesn't identify which user the selected value is associated to.

2023-10-24 09:08 UTC, robinandrewdevilliers commented on server/controllers/recommendation/reviewPractitionersConcernsController.ts
> +    })
fixed

2023-10-24 09:30 UTC, DarrenW-HMPPS approved these changes

2023-10-24 10:08 UTC, merged